### ISSUE TITLE
Cannot upload screenshot - Failed to parse response from server

### ISSUE THREAD

**Issue by datExo** [olav-st/screencloud#262]
I have a problem with uploading my screenshots to screencloud.
After im taking screenshot - application is waiting a minute and then shows an error:

```
Upload failed!
Failed to parse response from server
```

tcpdump shows how application first goes on "api.screencloud.net" and then goes on domain "host1.screencloud.net" but this domain does not exist

Full paste of tcpdump and dig: http://pastebin.com/hazpsa70

**Comment by galaxyx7** [comment]
I'm having the exact same problem (30.01.2017)

**Comment by rjbrooksjr** [comment]
Same, and also just realized I can't get to screencloud.net

**Comment by olav-st** [comment]
The server seems to have problems accepting uploaded images. I'll look into it.

**Comment by rikai** [comment]
@olav-st I now get the following message:

> Upload failed!
> Uploading has been disabled due to a server problem. Please try again later.

As well as any images hosted on screencloud seem to now not load, and if i try to load their direct links, give "403 Forbidden" errors.

**Comment by tomsieron** [comment]
Any est of it getting fixed?

**Comment by IrinaSvirkina** [comment]
"As well as any images hosted on screencloud seem to now not load, and if i try to load their direct links, give "403 Forbidden" errors."
I have the same problem. Direct link gives 403 Forbidden.

**Comment by OnkelTem** [comment]
Same problem for the third day. Doesn't work anymore both on Windows and Linux.

```
Upload failed!
Uploading has been disabled due to a server problem. Please try again later.
```

**Comment by olav-st** [comment]
The problem should be fixed now!

**Comment by OnkelTem** [comment]
Thank you!

**Comment by dalethedeveloper** [comment]
This behavior has manifested again.  v1.3.0 windows 

Also screencloud.net appears to be timing out: 504 Gateway Time-out

**Comment by galaxyx7** [comment]
Same here - Windows v1.3.0

**Comment by OnkelTem** [comment]
The problem persists.
Really hope it will be fixed soon. I love ScreenCloud service!

**Comment by olav-st** [comment]
See https://github.com/olav-st/screencloud/issues/266

**Comment by OnkelTem** [comment]
Works again! Eee!
Long Live ScreenCloud!

P.S. /me feels ready to bring in some money for the good of the project!

**Comment by romeozi** [comment]
At the moment I'm getting the same error...

**Comment by galaxyx7** [comment]
Again, same error.

Kind regards,
Romano
